# Generated by Django 4.0.5 on 2022-06-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_panchayathsecretaryextra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
